# Generated by Django 4.0.4 on 2022-06-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpjcpf_emp', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresasEstabelecimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpjcpf_emp', models.CharField(max_length=50)),
                ('cnpjcpf_est', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresasPrestadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpjcpf_emp', models.CharField(max_length=50)),
                ('cnpjcpf_pres', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpjcpf_emp', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpjcpf_emp', models.CharField(max_length=50)),
                ('cnpjcpf_est', models.CharField(max_length=50)),
                ('cnpjcpf_pres', models.CharField(max_length=50)),
                ('numero_nota', models.IntegerField()),
                ('serie', models.CharField(max_length=50)),
                ('deducao', models.FloatField()),
                ('valor_servico', models.FloatField()),
                ('dh_emissao', models.DateTimeField()),
                ('descricao', models.CharField(max_length=50)),
                ('codigo_servico', models.FloatField()),
                ('cancelada', models.BooleanField()),
                ('iss_retido', models.BooleanField()),
                ('aliq_iss', models.FloatField()),
                ('valor_iss', models.FloatField()),
                ('valor_pis', models.FloatField()),
                ('valor_cofins', models.FloatField()),
                ('valor_csll', models.FloatField()),
                ('valor_irrf', models.FloatField()),
                ('valor_inss', models.FloatField()),
                ('serie_rps', models.CharField(max_length=50)),
                ('rps', models.IntegerField()),
                ('codigo_verificacao', models.CharField(max_length=50)),
                ('nome_pdf', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prestadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpjcpf_prest', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_servico', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
    ]
