# Generated by Django 4.0.4 on 2022-06-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estabelecimentos',
            old_name='cnpjcpf_emp',
            new_name='cnpjcpf_est',
        ),
    ]
