# Generated by Django 4.0.4 on 2022-06-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_rename_cnpjcpf_emp_estabelecimentos_cnpjcpf_est'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='cnpjcpf_pres',
            new_name='cnpjcpf_prest',
        ),
    ]
