# Generated by Django 4.0.4 on 2022-06-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_alter_notas_cancelada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='iss_retido',
            field=models.BooleanField(default=False),
        ),
    ]
