# Generated by Django 4.0.4 on 2022-06-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_notas_iss_retido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='aliq_iss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='codigo_servico',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='deducao',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='valor_cofins',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='valor_csll',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='valor_inss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='valor_irrf',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='valor_iss',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='valor_pis',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notas',
            name='valor_servico',
            field=models.FloatField(default=0),
        ),
    ]
