# Generated by Django 4.0.4 on 2022-06-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_alter_notas_iss_retido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='iss_retido',
        ),
    ]
