# Generated by Django 4.0.4 on 2022-06-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_remove_notas_iss_retido'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='iss_retido',
            field=models.CharField(blank=True, default='N', max_length=2, null=True),
        ),
    ]
