# Generated by Django 4.0.4 on 2022-06-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_notas_iss_retido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='aliq_iss',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='iss_retido',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='valor_cofins',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='valor_csll',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='valor_inss',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='valor_irrf',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='valor_iss',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='valor_pis',
        ),
    ]
