# Generated by Django 4.0.4 on 2022-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_remove_notas_aliq_iss_remove_notas_iss_retido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='aliq_iss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='iss_retido',
            field=models.CharField(default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='notas',
            name='valor_cofins',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='valor_csll',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='valor_inss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='valor_irrf',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='valor_iss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='valor_pis',
            field=models.FloatField(default=0),
        ),
    ]
