# Generated by Django 4.0.4 on 2022-06-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0012_notas_aliq_iss_notas_iss_retido_notas_valor_cofins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='serie_rps',
        ),
    ]
