# Generated by Django 4.0.4 on 2022-06-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_remove_notas_codigo_verificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='codigo_verificacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='nome_pdf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notas',
            name='rps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notas',
            name='serie_rps',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
