# Generated by Django 4.0.4 on 2022-06-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0015_notas_codigo_verificacao_notas_nome_pdf_notas_rps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='aliq_iss',
        ),
    ]
