# Generated by Django 4.0.4 on 2022-06-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0016_remove_notas_aliq_iss'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='aliq_iss',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
