# Generated by Django 4.0.4 on 2022-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0020_alter_notas_rps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='serie_rps',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
