# Generated by Django 4.0.4 on 2022-07-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0021_alter_notas_serie_rps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpjcpf_est', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('day', models.PositiveIntegerField(default=0, verbose_name='dia')),
                ('hour', models.TimeField(auto_now_add=True, verbose_name='hora')),
            ],
        ),
        migrations.CreateModel(
            name='Permissoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=50)),
                ('perfil', models.PositiveIntegerField(default=2)),
                ('notificar', models.BooleanField(default=False)),
                ('permissoes', models.ManyToManyField(to='api_app.permissoes')),
            ],
        ),
    ]
