# Generated by Django 4.0.4 on 2022-07-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0022_parametros_permissoes_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
