# Generated by Django 4.0.4 on 2022-07-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0023_usuarios_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='hour',
            field=models.TimeField(auto_now=True, verbose_name='hora'),
        ),
    ]
